name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: |
        # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA .
        # docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$GITHUB_SHA
